version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
