#include "userspace.h"
#include <iostream>

void help(const char *executableName) {
    std::cout << "Tetra: a quadlet definition helper from Fyra Labs" << std::endl;
    std::cout << "Usage: " << executableName << " recipe.yaml userconf.yaml" << std::endl;
    std::cout << "recipe.yaml: yaml-defined recipe for a quadlet service. See documentation for information on syntax." << std::endl; // insert link eventually
    std::cout << "userconf.yaml: user-defined yaml containing user overrides for recipe elements, generated by Fyra Dashboard."
              << std::endl; // name is a placeholder because we don't have a name for UM server dashboard
}
